version: "3"
services:
  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 5s
  server:
    build: ./server
    environment:
      REDIS_HOST: redis
      PORT: 3000
    healthcheck:
      test: wget -O- http://localhost:$${PORT}/health
      interval: 5s
      start_period: 10s
      timeout: 5s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
  client:
    build: ./client
    depends_on:
      server:
        condition: service_healthy
